name: "Create release"

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Create release"
        default: ""
        required: true
      since:
        description: "Changelog since"
        default: ""
        required: false